// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7pj1fN5fdDO-eICOg-AKrgiNMbHPKd4',
    appId: '1:712407355856:web:d021605180d934ed4469d5',
    messagingSenderId: '712407355856',
    projectId: 'hopeon-2b8ef',
    authDomain: 'hopeon-2b8ef.firebaseapp.com',
    databaseURL: 'https://hopeon-2b8ef-default-rtdb.firebaseio.com',
    storageBucket: 'hopeon-2b8ef.firebasestorage.app',
    measurementId: 'G-YY0FS4TXP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnkP1-rgSoxZRpuhG-nPovvzx8m5_ft24',
    appId: '1:712407355856:android:bdae8547e7cde8744469d5',
    messagingSenderId: '712407355856',
    projectId: 'hopeon-2b8ef',
    databaseURL: 'https://hopeon-2b8ef-default-rtdb.firebaseio.com',
    storageBucket: 'hopeon-2b8ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gwhxwA_7eTokQWegwyTQWjPSIrMkz6c',
    appId: '1:712407355856:ios:f1a2d17b929c55854469d5',
    messagingSenderId: '712407355856',
    projectId: 'hopeon-2b8ef',
    databaseURL: 'https://hopeon-2b8ef-default-rtdb.firebaseio.com',
    storageBucket: 'hopeon-2b8ef.firebasestorage.app',
    iosBundleId: 'com.example.hopeonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gwhxwA_7eTokQWegwyTQWjPSIrMkz6c',
    appId: '1:712407355856:ios:f1a2d17b929c55854469d5',
    messagingSenderId: '712407355856',
    projectId: 'hopeon-2b8ef',
    databaseURL: 'https://hopeon-2b8ef-default-rtdb.firebaseio.com',
    storageBucket: 'hopeon-2b8ef.firebasestorage.app',
    iosBundleId: 'com.example.hopeonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-7pj1fN5fdDO-eICOg-AKrgiNMbHPKd4',
    appId: '1:712407355856:web:106b9cd6e7b99e224469d5',
    messagingSenderId: '712407355856',
    projectId: 'hopeon-2b8ef',
    authDomain: 'hopeon-2b8ef.firebaseapp.com',
    databaseURL: 'https://hopeon-2b8ef-default-rtdb.firebaseio.com',
    storageBucket: 'hopeon-2b8ef.firebasestorage.app',
    measurementId: 'G-YF7WPNVK2D',
  );
}
